In [1]:
import re
import os
import pandas as pd
import numpy as np

### 1.look at CPU times for all threads, in particular where the values are huge

load data of thread dump

In [2]:
rootdir ='C:\\Users\\li\\Downloads\\project\\talkback-FUSION-201811072237-gdcpl4173\\fusion\\logs\\server\\'
filename = []
def listdir(path, list_name):
    for file in os.listdir(path):
        if 'thread' in file:
            if 'bz2' not in file:
                list_name.append(file)
listdir(rootdir,filename)

In [3]:
len(filename)

168

In [4]:
data = ''
for name in filename:
    direction = rootdir + name
    data += open(direction).read()

find all information of pending proposal sequence and output proposal sequence, especially time

In [5]:
pattern = re.compile("PendingProposalSequence:\[\[(.*?)\]\[(.*?)\]\]\-0:\s+(\d+)\s+(\d+)\s+(\d+)\s+([A-Z]+)[\s\S]+?OutputProposalSequence:\[\[(.*?)\]\[(.*?)\]\]\-0:\s+(\d+)\s+(\d+)\s+(\d+)\s+([A-Z]+)")

In [6]:
pair = pattern.findall(data)

In [7]:
df= pd.DataFrame(pair)
df.rename(columns={0:'pendingNodeId',1:'pendingDSM',2:'cputime1',3:'usertime1',4:'id1',5:'status1',6:'outputNodeId',7:'outputDSM',8:'cputime2',9:'usertime2',10:'id2',11:'status2'},inplace=True)
df

pendingNodeId  \
0      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
2      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
3      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
4      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
5      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
6      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
7      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
8      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
9      eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
12     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
13     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
14     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
15     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
16     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
17     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
18     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
19     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
20     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
21     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
22     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
23     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
24     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
25     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
26     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
27     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
28     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
29     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
...                                     ...   
11727  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11728  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11729  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11730  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11731  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11732  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11733  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11734  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11735  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11736  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11737  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11738  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11739  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11740  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11741  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11742  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11743  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11744  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11745  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11746  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11747  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11748  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11749  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11750  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11751  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11752  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11753  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11754  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11755  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11756  eb4f7901-c43e-423e-aa8d-7c3d1f001460   

                                         pendingDSM cputime1 usertime1  \
0              df95e010-d455-11e8-a542-0090fa4225ec       17        10   
1              73474f26-b362-11e8-a542-0090fa4225ec        4         0   
2              5bdf2e62-b362-11e8-a542-0090fa4225ec        9         0   
3              4aae3d8b-b362-11e8-a542-0090fa4225ec      558       530   
4              ed7bc03b-81ee-11e8-a542-0090fa4225ec      460       430   
5              cd14f846-7161-11e8-a542-0090fa4225ec     8626      8110   
6              ccfeb11c-7161-11e8-a542-0090fa4225ec      774       730   
7              41f8918e-60e0-11e8-a542-0090fa4225ec      267       250   
8              41e24a64-60e0-11e8-a542-0090fa4225ec     1068      1010   
9              41d79bfa-60e0-11e8-a542-0090fa4225ec        2         0   
10             83bc2c09-5b62-11e8-a542-0090fa4225ec        1         0   
11             f3e1ce88-55df-11e8-a542-0090fa4225ec        2         0   
12             f3cd350a-55df-11e8-a542-0090fa4225ec      782       740   
13             f3b714ea-55df-11e8-a542-0090fa4225ec      478       450   
14   

In [8]:
df.describe()

pendingNodeId  \
count                                  11757   
unique                                     1   
top     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
freq                                   11757   

                                  pendingDSM cputime1 usertime1      id1  \
count                                  11757    11757     11757    11757   
unique                                    71      291       129       71   
top     d2397ecb-1481-11e8-a542-0090fa4225ec        0         0  5342661   
freq                                     168     1520      5102      168   

        status1                          outputNodeId  \
count     11757                                 11757   
unique        1                                     1   
top     WAITING  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
freq      11757                                 11757   

                                   outputDSM cputime2 usertime2    id2  \
count                                  11757    11757     11757  11757   
unique                                    71    11128      8041     71   
top     d2397ecb-1481-11e8-a542-0090fa4225ec       22        10    531   
freq                                     168      168       168    168   

        status2  
count     11757  
unique        1  
top     WAITING  
freq      11757

not all DSM appears in each thread-dump file because there are some differences, 71 unqie DSM and 168 hourly thread-dump file should appear over 11757 times, I will find the difference later in part 3

In [9]:
71 * 168 - 11757

171

In [10]:
df.cputime1 = pd.to_numeric(df.cputime1, errors='coerce')
df.cputime2 = pd.to_numeric(df.cputime2, errors='coerce')
df.usertime1 = pd.to_numeric(df.usertime1, errors='coerce')
df.usertime2 = pd.to_numeric(df.usertime2, errors='coerce')

In [11]:
df['cputime2'].describe()

count    1.175700e+04
mean     8.172184e+05
std      2.516739e+06
min      2.200000e+01
25%      3.282850e+05
50%      3.819800e+05
75%      4.896340e+05
max      1.992437e+07
Name: cputime2, dtype: float64

In [12]:
average = np.mean(df['cputime2'])
average

817218.4053755209

get the strange CPU time info (CPU time greater than average)

In [14]:
high = df[df['cputime2']>average]
high

pendingNodeId  \
45     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
50     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
54     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
56     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
113    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
118    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
122    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
124    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
181    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
186    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
190    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
192    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
249    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
254    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
258    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
260    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
317    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
322    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
326    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
328    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
385    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
390    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
394    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
396    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
453    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
458    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
462    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
464    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
521    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
526    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
...                                     ...   
11246  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11248  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11308  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11313  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11317  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11319  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11379  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11384  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11388  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11390  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11450  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11455  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11459  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11461  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11521  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11526  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11530  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11532  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11592  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11597  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11601  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11603  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11663  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11668  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11672  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11674  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11734  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11739  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11743  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11745  eb4f7901-c43e-423e-aa8d-7c3d1f001460   

                                 pendingDSM  cputime1  usertime1  id1  \
45     09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
50     d49450d6-147c-11e8-a542-0090fa4225ec         4          0  650   
54     d489a24c-147c-11e8-a542-0090fa4225ec    168965     160190  641   
56     a8b981f9-147c-11e8-a542-0090fa4225ec     28901      27740  633   
113    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
118    d49450d6-147c-11e8-a542-0090fa4225ec         4          0  650   
122    d489a24c-147c-11e8-a542-0090fa4225ec    168965     160190  641   
124    a8b981f9-147c-11e8-a542-0090fa4225ec     28901      27740  633   
181    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
186    d49450d6-147c-11e8-a542-0090fa4225ec         4          0  650   
190    d489a24c-147c-11e8-a542-0090fa4225ec    168965     160190  641   
192    a8b981f9-147c-11e8-a542-0090fa4225ec     28914      27750  633   
249    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
254    d49450d6-147c-11e8-a542-0090fa4225ec         4          0  650   
258    d489a24c-147c

In [15]:
high['pendingDSM'].describe()

count                                      672
unique                                       4
top       09f68b04-147d-11e8-a542-0090fa4225ec
freq                                       168
Name: pendingDSM, dtype: object

there are information which use huge amount of CPU time,they may be the culprit

In [16]:
high['pendingDSM'].unique()

array(['09f68b04-147d-11e8-a542-0090fa4225ec',
       'd49450d6-147c-11e8-a542-0090fa4225ec',
       'd489a24c-147c-11e8-a542-0090fa4225ec',
       'a8b981f9-147c-11e8-a542-0090fa4225ec'], dtype=object)

an example info in each hour

In [17]:
df[df['pendingDSM'] == '09f68b04-147d-11e8-a542-0090fa4225ec']

pendingNodeId  \
45     eb4f7901-c43e-423e-aa8d-7c3d1f001460   
113    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
181    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
249    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
317    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
385    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
453    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
521    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
589    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
657    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
725    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
793    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
861    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
929    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
997    eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1065   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1133   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1201   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1269   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1337   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1405   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1473   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1541   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1609   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1677   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1745   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1813   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1881   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
1949   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
2017   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
...                                     ...   
9675   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
9746   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
9817   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
9888   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
9959   eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10030  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10101  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10172  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10243  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10314  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10385  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10456  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10527  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10598  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10669  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10740  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10811  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10882  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
10953  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11024  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11095  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11166  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11237  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11308  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11379  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11450  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11521  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11592  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11663  eb4f7901-c43e-423e-aa8d-7c3d1f001460   
11734  eb4f7901-c43e-423e-aa8d-7c3d1f001460   

                                 pendingDSM  cputime1  usertime1  id1  \
45     09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
113    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
181    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
249    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
317    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
385    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
453    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
521    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
589    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
657    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
725    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
793    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
861    09f68b04-147d-11e8-a542-0090fa4225ec    385252     367280  730   
929    09f68b04-147d-11e8-a542-0090fa4225ec    385254     367280  730   
997    09f68b04-147d

### 2.compare CPU time for each of these threads across each hourly thread-dump logFile

in a busy system, threads should have ever increasing CPU time, so I get the DSM and cpu times

In [18]:
time_ptn = re.compile('OutputProposalSequence:\[\[.*?\]\[(.*?)\]\]\-0:\s+(\d+)\s+\d+\s+\d+\s+[A-Z]+')

In [19]:
data = ''
for name in filename:
    direction = rootdir + name
    data += open(direction).read()

In [20]:
DSM_time = time_ptn.findall(data)

In [21]:
DSM = {}
for i in range(len(DSM_time)):
    dsmId = DSM_time[i][0]
    cputime = int(DSM_time[i][1])
    if dsmId in DSM:
        DSM[dsmId].append(cputime)
    else:
        DSM[dsmId] = []
        DSM[dsmId].append(cputime)

In [22]:
strange_dsm = []
for dsm, time in DSM.items():
    for i in range(len(time)-1):
        if time[i+1] - time[i] < 0:
            strange_dsm.append(dsm)

but seems like all threads are increasing CPU time for each hour

In [23]:
strange_dsm

[]

### 3.they do not appear in every hourly thread dump file

In [24]:
not168 = []
for k,v in DSM.items():
    if len(v) != 168:
        not168.append(k)
not168

['df3f0f02-df66-11e8-a542-0090fa4225ec',
 'df32b2e1-df66-11e8-a542-0090fa4225ec',
 'df32b2e2-df66-11e8-a542-0090fa4225ec']

In [26]:
len(DSM['df3f0f02-df66-11e8-a542-0090fa4225ec'])

111

In [27]:
len(DSM['df32b2e1-df66-11e8-a542-0090fa4225ec'])

111

In [28]:
len(DSM['df32b2e2-df66-11e8-a542-0090fa4225ec'])

111